"""
Domain boundary for Crypto Helper.
Auto-generated by ProtoGraph App Onboarding — edit freely.
"""

DOMAIN_CLASSES = ['Thing']
DOMAIN_RELATIONSHIPS = []
WRITE_PERMISSIONS = []
MODE = 'hybrid'
ACCEPTS_DELEGATION = False
AGENT_PEERS = []
