"""
Domain boundary for Crypto Helper.
Auto-generated by ProtoGraph App Onboarding — edit freely.
"""

# OWL classes this agent can reason about
DOMAIN_CLASSES = ['Thing']

# Relationship types in scope
DOMAIN_RELATIONSHIPS = []

# Write permissions granted
WRITE_PERMISSIONS = []

# Interaction mode: 'action' | 'conversational' | 'hybrid'
MODE = 'hybrid'
