"""
Hybrid Semantic-Structural Clustering Router v2
================================================

Improvements over v1:
1. Coherence score uses actual embedding similarity (not just type/team)
2. Incremental re-clustering support for background updates
3. Cluster assignment persistence to ArangoDB
4. Edge weights properly used in affinity calculation
5. Configurable clustering parameters via API

Drop-in replacement for EnhancedNeuralGraphRouter.
"""

import os
import hashlib
import time
from datetime import datetime
from typing import List, Dict, Any, Optional, Set, Tuple
from dataclasses import dataclass, field
from collections import defaultdict
import numpy as np
import re
import json

# ArangoDB
from arango import ArangoClient

# For embeddings
import requests


# =============================================================================
# CONFIGURATION
# =============================================================================

ARANGO_HOST = os.getenv("ARANGO_HOST", "http://localhost:8529")
ARANGO_DB = os.getenv("ARANGO_DB", "AUTO_DB")
ARANGO_USER = os.getenv("ARANGO_USER", "root")
ARANGO_PASSWORD = os.getenv("ARANGO_PASSWORD", "devpass")

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://10.10.80.99:4001")
EMBEDDING_MODEL = os.getenv("OLLAMA_EMBEDDING_MODEL", "nomic-embed-text:latest")
SLM_MODEL = os.getenv("OLLAMA_SLM_MODEL", "gemma2:2b")

# Schema collections to exclude
SCHEMA_COLLECTIONS = {
    'ontology_concepts', 'concepts', 'ontology_taxonomies',
    'taxonomy_schemes', 'taxonomy_terms', 'taxonomies',
    'ontology_relationships', 'ontology_edges', 'relationship_types',
    'ontology_properties', 'schema_definitions', 'system_config', 'meta',
    'cluster_assignments', 'cluster_cards',  # Our persistence collections
}

# Edge collections for traversal
EDGE_COLLECTIONS = [
    'CONTAINS', 'PRODUCES', 'REFERENCES', 'LEADS_TO', 'STARTS_WITH',
    'IMPLEMENTS', 'TESTED_BY', 'USES', 'DEPENDS_ON', 'RELATES_TO',
]

# Propagation weights by relationship type
PROPAGATION_WEIGHTS = {
    'IMPLEMENTS': 0.9,
    'TESTED_BY': 0.85,
    'USES': 0.8,
    'DEPENDS_ON': 0.75,
    'PRODUCES': 0.7,
    'REFERENCES': 0.6,
    'CONTAINS': 0.6,
    'LEADS_TO': 0.5,
    'STARTS_WITH': 0.4,
    'RELATES_TO': 0.5,
}

# Hybrid clustering parameters (defaults, can be overridden)
DEFAULT_CLUSTERING_CONFIG = {
    "knn_k": 5,                      # Number of nearest neighbors
    "semantic_weight": 0.5,          # Weight for embedding similarity
    "edge_weight": 0.3,              # Weight for edge existence
    "type_bonus": 0.1,               # Bonus for same node type
    "team_bonus": 0.1,               # Bonus for same team
    "merge_threshold": 0.4,          # Minimum affinity to merge clusters
    "min_cluster_size": 2,           # Minimum nodes per cluster
    "max_cluster_size": 20,          # Maximum nodes per cluster
}

# Routing thresholds
ACTIVATION_THRESHOLD = 0.25
MAX_HOPS = 4
MAX_ACTIVE_AGENTS = 20
SIGNAL_DECAY = 0.75

# MITRE pattern
MITRE_PATTERN = re.compile(r'T\d{4}(?:\.\d{3})?', re.IGNORECASE)

# Known entities
KNOWN_ENTITIES = {
    'mimikatz', 'cobalt strike', 'beacon', 'powershell', 'psexec',
    'wmi', 'winrm', 'ssh', 'rdp', 'smb', 'kerberos', 'ntlm',
    'credential', 'persistence', 'lateral movement', 'exfiltration',
    'discovery', 'execution', 'privilege escalation', 'defense evasion',
    'c2', 'command and control', 'initial access', 'reconnaissance',
    'atomic red team', 'caldera', 'sliver', 'metasploit', 'empire',
}


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class GraphNode:
    """Node from ArangoDB with full metadata"""
    id: str
    label: str
    node_type: str
    team_cluster: str
    description: str
    tags: List[str]
    properties: Dict[str, Any] = field(default_factory=dict)
    embedding: Optional[np.ndarray] = None


@dataclass
class GraphEdge:
    """Edge from ArangoDB"""
    id: str
    source: str
    target: str
    edge_type: str
    weight: float = 1.0


@dataclass
class ClusterCard:
    """
    Structured, auditable description of a cluster.
    Compiled from graph data, not generated by an LLM.
    """
    cluster_id: str
    node_ids: Set[str]
    node_count: int
    type_distribution: Dict[str, int]
    primary_type: str
    team_distribution: Dict[str, int]
    primary_team: str
    mitre_techniques: Set[str]
    tools: Set[str]
    internal_edge_count: int
    external_edge_count: int
    edge_type_distribution: Dict[str, int]
    exemplar_paths: List[Dict[str, Any]]
    core_node_ids: List[str]
    core_node_labels: List[str]
    keywords: Set[str]
    centroid_embedding: Optional[np.ndarray] = None
    coherence_score: float = 0.0
    connectivity_score: float = 0.0
    created_at: str = ""
    updated_at: str = ""
    
    def to_summary_text(self) -> str:
        """Generate human-readable summary from card data"""
        type_str = ", ".join(f"{v} {k}" for k, v in 
                            sorted(self.type_distribution.items(), key=lambda x: -x[1])[:3])
        mitre_str = ", ".join(list(self.mitre_techniques)[:5]) if self.mitre_techniques else "none"
        tools_str = ", ".join(list(self.tools)[:5]) if self.tools else "none"
        
        return (
            f"[{self.primary_team.upper()}] {self.node_count} artifacts ({type_str}). "
            f"MITRE: {mitre_str}. Tools: {tools_str}. "
            f"Core: {', '.join(self.core_node_labels[:3])}."
        )
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize for API response"""
        return {
            "cluster_id": self.cluster_id,
            "node_count": self.node_count,
            "node_ids": list(self.node_ids)[:50],
            "type_distribution": self.type_distribution,
            "primary_type": self.primary_type,
            "team_distribution": self.team_distribution,
            "primary_team": self.primary_team,
            "mitre_techniques": list(self.mitre_techniques),
            "tools": list(self.tools),
            "internal_edges": self.internal_edge_count,
            "external_edges": self.external_edge_count,
            "edge_types": self.edge_type_distribution,
            "exemplar_paths": self.exemplar_paths,
            "core_nodes": self.core_node_labels[:5],
            "keywords": list(self.keywords)[:15],
            "coherence_score": self.coherence_score,
            "connectivity_score": self.connectivity_score,
            "summary": self.to_summary_text(),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }
    
    def to_storage_dict(self) -> Dict[str, Any]:
        """Serialize for ArangoDB storage (no numpy arrays)"""
        d = self.to_dict()
        d["node_ids"] = list(self.node_ids)  # Full list for storage
        # Don't store embedding in JSON - too large
        return d


@dataclass
class ClusterAgent:
    """Agent backed by a ClusterCard"""
    agent_id: str
    card: ClusterCard
    activation_count: int = 0
    
    @property
    def cluster_id(self) -> str:
        return self.card.cluster_id
    
    @property
    def node_ids(self) -> Set[str]:
        return self.card.node_ids


@dataclass
class ActivationResult:
    """Result of neural routing"""
    query: str
    entry_agents: List[str]
    entry_scores: Dict[str, Dict[str, float]]
    activated_agents: List[str]
    contributing_agents: List[str]
    propagation_path: List[Dict[str, Any]]
    contexts: Dict[str, str]
    cluster_cards: Dict[str, Dict[str, Any]]
    nodes_traversed: int
    total_time_ms: float


# =============================================================================
# OLLAMA CLIENT
# =============================================================================

class OllamaClient:
    """Client for Ollama embeddings and generation"""
    
    def __init__(self, host: str = OLLAMA_HOST):
        self.host = host.rstrip('/')
        self.embedding_cache: Dict[str, np.ndarray] = {}
        self._healthy = None
    
    def health_check(self) -> bool:
        if self._healthy is not None:
            return self._healthy
        try:
            response = requests.get(f"{self.host}/api/tags", timeout=5)
            self._healthy = response.status_code == 200
            return self._healthy
        except:
            self._healthy = False
            return False
    
    def get_embedding(self, text: str, model: str = EMBEDDING_MODEL) -> Optional[np.ndarray]:
        cache_key = hashlib.md5(f"{model}:{text[:500]}".encode()).hexdigest()
        if cache_key in self.embedding_cache:
            return self.embedding_cache[cache_key]
        
        try:
            response = requests.post(
                f"{self.host}/api/embeddings",
                json={"model": model, "prompt": text[:1000]},
                timeout=30
            )
            if response.status_code == 200:
                data = response.json()
                if "embedding" in data:
                    embedding = np.array(data["embedding"])
                elif "embeddings" in data:
                    embedding = np.array(data["embeddings"][0])
                else:
                    return None
                self.embedding_cache[cache_key] = embedding
                return embedding
        except Exception as e:
            print(f"⚠️ Embedding error: {e}")
        return None
    
    def generate_context(self, cluster_card: ClusterCard, query: str, model: str = SLM_MODEL) -> Optional[str]:
        """Generate context using ClusterCard data (grounded, not improvised)"""
        card_facts = (
            f"Cluster contains {cluster_card.node_count} artifacts, "
            f"primarily {cluster_card.primary_type}s owned by {cluster_card.primary_team}.\n"
            f"MITRE techniques: {', '.join(list(cluster_card.mitre_techniques)[:5]) or 'none'}.\n"
            f"Tools: {', '.join(list(cluster_card.tools)[:5]) or 'none'}.\n"
            f"Core artifacts: {', '.join(cluster_card.core_node_labels[:3])}."
        )
        
        prompt = f"""Given these FACTS about a knowledge cluster:
{card_facts}

Query: {query}

Based ONLY on the facts above, write ONE sentence (max 25 words) explaining how this cluster helps answer the query.
If the facts don't relate to the query, respond with exactly: NOT_RELEVANT"""

        try:
            response = requests.post(
                f"{self.host}/api/generate",
                json={
                    "model": model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"num_predict": 60, "temperature": 0.2}
                },
                timeout=60
            )
            if response.status_code == 200:
                text = response.json().get("response", "").strip()
                if "NOT_RELEVANT" in text.upper():
                    return None
                return text
        except Exception as e:
            print(f"⚠️ Generation error: {e}")
        return None


# =============================================================================
# ENTITY EXTRACTION
# =============================================================================

def extract_mitre_ids(text: str) -> Set[str]:
    """Extract MITRE ATT&CK technique IDs"""
    matches = MITRE_PATTERN.findall(text)
    return {m.upper() for m in matches}


def extract_tools(text: str) -> Set[str]:
    """Extract known tool names"""
    text_lower = text.lower()
    return {entity for entity in KNOWN_ENTITIES if entity in text_lower}


def extract_keywords(text: str) -> Set[str]:
    """Extract meaningful keywords"""
    stop_words = {'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been',
                  'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
                  'would', 'could', 'should', 'may', 'might', 'must', 'shall',
                  'can', 'need', 'to', 'of', 'in', 'for', 'on', 'with', 'at',
                  'by', 'from', 'as', 'into', 'through', 'during', 'before',
                  'after', 'above', 'below', 'and', 'but', 'or', 'nor', 'so',
                  'yet', 'both', 'either', 'neither', 'not', 'only', 'own',
                  'same', 'than', 'too', 'very', 'just', 'this', 'that', 'it'}
    
    words = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', text.lower())
    return {w for w in words if len(w) > 2 and w not in stop_words}


# =============================================================================
# HYBRID CLUSTERING (IMPROVED)
# =============================================================================

class HybridClusterer:
    """
    Clusters nodes using semantic similarity + structural affinity.
    
    Improvements:
    - Uses actual edge weights from PROPAGATION_WEIGHTS
    - Configurable parameters
    - Caches embeddings for incremental updates
    """
    
    def __init__(self, ollama: OllamaClient, config: Optional[Dict[str, Any]] = None):
        self.ollama = ollama
        self.config = {**DEFAULT_CLUSTERING_CONFIG, **(config or {})}
        self.embedding_cache: Dict[str, np.ndarray] = {}
    
    def cluster(
        self,
        nodes: Dict[str, GraphNode],
        edges: List[GraphEdge],
        existing_assignments: Optional[Dict[str, str]] = None
    ) -> Tuple[Dict[str, str], Dict[str, np.ndarray]]:
        """
        Cluster nodes and return (node_id -> cluster_id, embeddings dict).
        
        If existing_assignments provided, only re-cluster nodes that are new
        or whose neighbors have changed significantly.
        """
        if not nodes:
            return {}, {}
        
        node_ids = list(nodes.keys())
        n = len(node_ids)
        
        print(f"🔬 Hybrid clustering {n} nodes...")
        print(f"   Config: semantic={self.config['semantic_weight']}, "
              f"edge={self.config['edge_weight']}, threshold={self.config['merge_threshold']}")
        
        # Build edge lookup with proper weights
        edge_set: Set[Tuple[str, str]] = set()
        edge_weights: Dict[Tuple[str, str], float] = {}
        
        for edge in edges:
            # Use PROPAGATION_WEIGHTS for the edge type
            weight = PROPAGATION_WEIGHTS.get(edge.edge_type, 0.5)
            pair = (edge.source, edge.target)
            pair_rev = (edge.target, edge.source)
            edge_set.add(pair)
            edge_set.add(pair_rev)
            # Take max weight if multiple edges exist
            edge_weights[pair] = max(edge_weights.get(pair, 0), weight)
            edge_weights[pair_rev] = max(edge_weights.get(pair_rev, 0), weight)
        
        # Compute embeddings
        print("   Computing embeddings...")
        embeddings: Dict[str, np.ndarray] = {}
        
        for node_id, node in nodes.items():
            # Check cache first
            if node_id in self.embedding_cache:
                embeddings[node_id] = self.embedding_cache[node_id]
                continue
            
            text = f"{node.label} {node.node_type} {node.description}"
            if node.tags:
                text += " " + " ".join(node.tags)
            
            emb = self.ollama.get_embedding(text[:500])
            if emb is not None:
                embeddings[node_id] = emb
                self.embedding_cache[node_id] = emb
        
        if len(embeddings) < 2:
            print("   ⚠️ Not enough embeddings, falling back to team-based clustering")
            return self._fallback_team_clustering(nodes), embeddings
        
        # Build affinity matrix
        print("   Building affinity matrix...")
        affinity = np.zeros((n, n))
        
        id_to_idx = {nid: i for i, nid in enumerate(node_ids)}
        
        for i, id_i in enumerate(node_ids):
            for j, id_j in enumerate(node_ids):
                if i == j:
                    affinity[i, j] = 1.0
                    continue
                
                score = 0.0
                
                # Semantic similarity (cosine)
                if id_i in embeddings and id_j in embeddings:
                    emb_i = embeddings[id_i]
                    emb_j = embeddings[id_j]
                    cos_sim = np.dot(emb_i, emb_j) / (np.linalg.norm(emb_i) * np.linalg.norm(emb_j) + 1e-9)
                    score += self.config["semantic_weight"] * max(0, cos_sim)
                
                # Edge existence bonus (using actual edge weight)
                if (id_i, id_j) in edge_set:
                    edge_w = edge_weights.get((id_i, id_j), 0.5)
                    score += self.config["edge_weight"] * edge_w
                
                # Type match bonus
                if nodes[id_i].node_type == nodes[id_j].node_type:
                    score += self.config["type_bonus"]
                
                # Team match bonus
                if nodes[id_i].team_cluster == nodes[id_j].team_cluster:
                    score += self.config["team_bonus"]
                
                affinity[i, j] = score
        
        # Agglomerative clustering
        print("   Running agglomerative clustering...")
        clusters = self._agglomerative_cluster(affinity, node_ids, nodes)
        
        # Stats
        cluster_counts = defaultdict(int)
        for cid in clusters.values():
            cluster_counts[cid] += 1
        
        print(f"   ✓ Created {len(set(clusters.values()))} clusters")
        sizes = sorted(cluster_counts.values(), reverse=True)
        print(f"   Sizes: {sizes[:10]}{'...' if len(sizes) > 10 else ''}")
        
        return clusters, embeddings
    
    def _agglomerative_cluster(
        self,
        affinity: np.ndarray,
        node_ids: List[str],
        nodes: Dict[str, GraphNode]
    ) -> Dict[str, str]:
        """Agglomerative clustering with configurable parameters"""
        n = len(node_ids)
        threshold = self.config["merge_threshold"]
        max_size = self.config["max_cluster_size"]
        
        cluster_assignments = {node_id: i for i, node_id in enumerate(node_ids)}
        cluster_members: Dict[int, Set[int]] = {i: {i} for i in range(n)}
        
        while True:
            best_merge = None
            best_score = threshold
            
            cluster_ids = list(cluster_members.keys())
            
            for ci in cluster_ids:
                if ci not in cluster_members:
                    continue
                if len(cluster_members[ci]) >= max_size:
                    continue
                
                for cj in cluster_ids:
                    if cj not in cluster_members or ci >= cj:
                        continue
                    if len(cluster_members[cj]) >= max_size:
                        continue
                    if len(cluster_members[ci]) + len(cluster_members[cj]) > max_size:
                        continue
                    
                    # Average linkage
                    total = sum(affinity[mi, mj] 
                               for mi in cluster_members[ci] 
                               for mj in cluster_members[cj])
                    count = len(cluster_members[ci]) * len(cluster_members[cj])
                    avg = total / count if count > 0 else 0
                    
                    if avg > best_score:
                        best_score = avg
                        best_merge = (ci, cj)
            
            if best_merge is None:
                break
            
            ci, cj = best_merge
            cluster_members[ci] = cluster_members[ci] | cluster_members[cj]
            del cluster_members[cj]
            
            for idx in cluster_members[ci]:
                cluster_assignments[node_ids[idx]] = ci
        
        # Normalize cluster IDs
        unique = sorted(set(cluster_assignments.values()))
        cluster_map = {old: f"cluster_{i}" for i, old in enumerate(unique)}
        
        return {nid: cluster_map[cid] for nid, cid in cluster_assignments.items()}
    
    def _fallback_team_clustering(self, nodes: Dict[str, GraphNode]) -> Dict[str, str]:
        """Fallback: cluster by team ownership"""
        return {nid: f"cluster_{node.team_cluster}" for nid, node in nodes.items()}


# =============================================================================
# CLUSTER CARD COMPILER (IMPROVED)
# =============================================================================

class ClusterCardCompiler:
    """
    Compiles ClusterCards from graph data.
    
    Improvements:
    - Coherence uses embedding similarity
    - Timestamps for tracking updates
    """
    
    def __init__(self, ollama: OllamaClient):
        self.ollama = ollama
    
    def compile(
        self,
        cluster_id: str,
        node_ids: Set[str],
        nodes: Dict[str, GraphNode],
        edges: List[GraphEdge],
        all_clusters: Dict[str, str],
        embeddings: Optional[Dict[str, np.ndarray]] = None
    ) -> ClusterCard:
        """Compile a ClusterCard for a cluster"""
        
        cluster_nodes = [nodes[nid] for nid in node_ids if nid in nodes]
        now = datetime.utcnow().isoformat()
        
        # Type distribution
        type_dist: Dict[str, int] = defaultdict(int)
        for node in cluster_nodes:
            type_dist[node.node_type] += 1
        primary_type = max(type_dist.keys(), key=lambda k: type_dist[k]) if type_dist else "unknown"
        
        # Team distribution
        team_dist: Dict[str, int] = defaultdict(int)
        for node in cluster_nodes:
            team_dist[node.team_cluster] += 1
        primary_team = max(team_dist.keys(), key=lambda k: team_dist[k]) if team_dist else "unknown"
        
        # Extract entities
        all_mitre: Set[str] = set()
        all_tools: Set[str] = set()
        all_keywords: Set[str] = set()
        
        for node in cluster_nodes:
            for text in [node.label, node.description] + node.tags:
                all_mitre.update(extract_mitre_ids(text))
                all_tools.update(extract_tools(text))
                all_keywords.update(extract_keywords(text))
        
        # Edge analysis
        internal_edges = 0
        external_edges = 0
        edge_type_dist: Dict[str, int] = defaultdict(int)
        
        for edge in edges:
            src_cluster = all_clusters.get(edge.source)
            tgt_cluster = all_clusters.get(edge.target)
            
            if src_cluster == cluster_id and tgt_cluster == cluster_id:
                internal_edges += 1
                edge_type_dist[edge.edge_type] += 1
            elif src_cluster == cluster_id or tgt_cluster == cluster_id:
                external_edges += 1
        
        # Core nodes
        node_degrees: Dict[str, int] = defaultdict(int)
        for edge in edges:
            if edge.source in node_ids and edge.target in node_ids:
                node_degrees[edge.source] += 1
                node_degrees[edge.target] += 1
        
        core_nodes = sorted(node_ids, key=lambda n: node_degrees.get(n, 0), reverse=True)[:5]
        core_labels = [nodes[n].label for n in core_nodes if n in nodes]
        
        # Exemplar paths
        exemplar_paths = self._find_exemplar_paths(node_ids, edges)
        
        # Centroid embedding
        centroid = None
        if self.ollama.health_check() and embeddings:
            cluster_embeddings = [embeddings[nid] for nid in node_ids if nid in embeddings]
            if cluster_embeddings:
                centroid = np.mean(cluster_embeddings, axis=0)
        
        # Coherence (improved: uses embeddings)
        coherence = self._compute_coherence(cluster_nodes, embeddings)
        
        # Connectivity
        max_internal = len(node_ids) * (len(node_ids) - 1) / 2
        connectivity = internal_edges / max_internal if max_internal > 0 else 0
        
        return ClusterCard(
            cluster_id=cluster_id,
            node_ids=node_ids,
            node_count=len(node_ids),
            type_distribution=dict(type_dist),
            primary_type=primary_type,
            team_distribution=dict(team_dist),
            primary_team=primary_team,
            mitre_techniques=all_mitre,
            tools=all_tools,
            internal_edge_count=internal_edges,
            external_edge_count=external_edges,
            edge_type_distribution=dict(edge_type_dist),
            exemplar_paths=exemplar_paths,
            core_node_ids=core_nodes,
            core_node_labels=core_labels,
            keywords=all_keywords,
            centroid_embedding=centroid,
            coherence_score=coherence,
            connectivity_score=connectivity,
            created_at=now,
            updated_at=now,
        )
    
    def _find_exemplar_paths(self, node_ids: Set[str], edges: List[GraphEdge]) -> List[Dict[str, Any]]:
        """Find common 2-hop patterns within cluster"""
        adj: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
        for edge in edges:
            if edge.source in node_ids and edge.target in node_ids:
                adj[edge.source].append((edge.target, edge.edge_type))
        
        patterns: Dict[str, int] = defaultdict(int)
        for src in adj:
            for mid, e1 in adj[src]:
                for tgt, e2 in adj.get(mid, []):
                    if tgt != src:
                        patterns[f"{e1}->{e2}"] += 1
        
        sorted_patterns = sorted(patterns.items(), key=lambda x: -x[1])[:5]
        return [{"pattern": p, "count": c} for p, c in sorted_patterns]
    
    def _compute_coherence(
        self, 
        nodes: List[GraphNode], 
        embeddings: Optional[Dict[str, np.ndarray]] = None
    ) -> float:
        """
        Compute semantic coherence using:
        1. Type homogeneity (30%)
        2. Team homogeneity (30%)
        3. Embedding similarity (40%)
        """
        if len(nodes) < 2:
            return 1.0
        
        # Type homogeneity
        types = [n.node_type for n in nodes]
        type_homo = max(types.count(t) for t in set(types)) / len(types)
        
        # Team homogeneity
        teams = [n.team_cluster for n in nodes]
        team_homo = max(teams.count(t) for t in set(teams)) / len(teams)
        
        # Embedding coherence
        emb_coherence = 0.5  # Default
        if embeddings:
            node_ids = [n.id for n in nodes if n.id in embeddings]
            if len(node_ids) >= 2:
                # Sample for efficiency (max 15 nodes)
                sample = node_ids[:15]
                sims = []
                for i, id_i in enumerate(sample):
                    for id_j in sample[i+1:]:
                        emb_i, emb_j = embeddings[id_i], embeddings[id_j]
                        sim = np.dot(emb_i, emb_j) / (np.linalg.norm(emb_i) * np.linalg.norm(emb_j) + 1e-9)
                        sims.append(max(0, sim))
                if sims:
                    emb_coherence = np.mean(sims)
        
        return 0.3 * type_homo + 0.3 * team_homo + 0.4 * emb_coherence


# =============================================================================
# PERSISTENCE LAYER
# =============================================================================

class ClusterPersistence:
    """
    Persists cluster assignments and cards to ArangoDB.
    Enables incremental updates without full re-clustering.
    """
    
    ASSIGNMENTS_COLLECTION = "cluster_assignments"
    CARDS_COLLECTION = "cluster_cards"
    
    def __init__(self, db):
        self.db = db
        self._ensure_collections()
    
    def _ensure_collections(self):
        """Create persistence collections if they don't exist"""
        for coll_name in [self.ASSIGNMENTS_COLLECTION, self.CARDS_COLLECTION]:
            if not self.db.has_collection(coll_name):
                self.db.create_collection(coll_name)
                print(f"✓ Created collection: {coll_name}")
    
    def save_assignments(self, assignments: Dict[str, str], method: str = "hybrid"):
        """Save node -> cluster assignments"""
        coll = self.db.collection(self.ASSIGNMENTS_COLLECTION)
        
        # Clear existing
        coll.truncate()
        
        # Save as single document with all assignments
        doc = {
            "_key": "current",
            "method": method,
            "assignments": assignments,
            "node_count": len(assignments),
            "cluster_count": len(set(assignments.values())),
            "updated_at": datetime.utcnow().isoformat(),
        }
        coll.insert(doc, overwrite=True)
        print(f"✓ Saved {len(assignments)} cluster assignments")
    
    def load_assignments(self) -> Optional[Dict[str, str]]:
        """Load saved cluster assignments"""
        coll = self.db.collection(self.ASSIGNMENTS_COLLECTION)
        try:
            doc = coll.get("current")
            if doc:
                print(f"✓ Loaded {doc['node_count']} cluster assignments ({doc['method']})")
                return doc["assignments"]
        except:
            pass
        return None
    
    def save_cards(self, cards: Dict[str, ClusterCard]):
        """Save cluster cards"""
        coll = self.db.collection(self.CARDS_COLLECTION)
        coll.truncate()
        
        for cluster_id, card in cards.items():
            doc = card.to_storage_dict()
            doc["_key"] = cluster_id.replace("/", "_")
            coll.insert(doc, overwrite=True)
        
        print(f"✓ Saved {len(cards)} cluster cards")
    
    def load_cards(self) -> Dict[str, Dict[str, Any]]:
        """Load saved cluster cards (as dicts, not ClusterCard objects)"""
        coll = self.db.collection(self.CARDS_COLLECTION)
        cards = {}
        for doc in coll.all():
            cluster_id = doc.get("cluster_id", doc["_key"])
            cards[cluster_id] = doc
        if cards:
            print(f"✓ Loaded {len(cards)} cluster cards")
        return cards
    
    def get_assignment_metadata(self) -> Optional[Dict[str, Any]]:
        """Get metadata about current assignments without loading all data"""
        coll = self.db.collection(self.ASSIGNMENTS_COLLECTION)
        try:
            doc = coll.get("current")
            if doc:
                return {
                    "method": doc.get("method"),
                    "node_count": doc.get("node_count"),
                    "cluster_count": doc.get("cluster_count"),
                    "updated_at": doc.get("updated_at"),
                }
        except:
            pass
        return None


# =============================================================================
# HYBRID CLUSTER ROUTER (IMPROVED)
# =============================================================================

class HybridClusterRouter:
    """
    Neural graph router using hybrid semantic-structural clustering.
    
    Improvements:
    - Persistence of cluster assignments
    - Incremental update support
    - Configurable clustering parameters
    """
    
    def __init__(self, ollama_client: Optional[OllamaClient] = None):
        self.ollama = ollama_client or OllamaClient()
        
        # ArangoDB connection
        self.client = ArangoClient(hosts=ARANGO_HOST)
        self.db = self.client.db(ARANGO_DB, username=ARANGO_USER, password=ARANGO_PASSWORD)
        
        # Persistence
        self.persistence = ClusterPersistence(self.db)
        
        # Data structures
        self.nodes: Dict[str, GraphNode] = {}
        self.edges: List[GraphEdge] = []
        self.agents: Dict[str, ClusterAgent] = {}
        self.node_to_agent: Dict[str, str] = {}
        self.agent_adjacency: Dict[str, Set[str]] = defaultdict(set)
        self.embeddings: Dict[str, np.ndarray] = {}
        
        self.available_edge_collections: List[str] = []
        self.clustering_method = "hybrid"
        self.clustering_config = DEFAULT_CLUSTERING_CONFIG.copy()
        
        self._initialized = False
    
    def initialize(
        self, 
        force_reload: bool = False, 
        method: str = "hybrid",
        use_cached: bool = True,
        config: Optional[Dict[str, Any]] = None
    ) -> bool:
        """
        Initialize the router.
        
        Args:
            force_reload: If True, re-cluster even if cached assignments exist
            method: "hybrid" or "label_propagation"
            use_cached: If True, try to load cached cluster assignments
            config: Override clustering parameters
        """
        if self._initialized and not force_reload:
            return True
        
        self.clustering_method = method
        if config:
            self.clustering_config.update(config)
        
        print("\n" + "="*60)
        print(f"HYBRID CLUSTER ROUTER v2 - INITIALIZATION")
        print(f"Method: {method}, Force: {force_reload}, Cached: {use_cached}")
        print("="*60)
        
        # Check Ollama
        if self.ollama.health_check():
            print(f"✓ Ollama connected at {OLLAMA_HOST}")
        else:
            print("⚠️ Ollama not available - limited functionality")
        
        # Load graph data
        self._validate_edge_collections()
        self._load_nodes()
        
        if not self.nodes:
            print("⚠️ No data nodes found")
            self._initialized = True
            return True
        
        self._load_edges()
        
        # Try to use cached assignments
        cached_assignments = None
        if use_cached and not force_reload:
            cached_assignments = self.persistence.load_assignments()
            
            if cached_assignments:
                # Validate cache: check if all current nodes have assignments
                current_nodes = set(self.nodes.keys())
                cached_nodes = set(cached_assignments.keys())
                
                missing = current_nodes - cached_nodes
                if missing:
                    print(f"⚠️ {len(missing)} new nodes since last clustering, re-clustering...")
                    cached_assignments = None
                else:
                    # Remove assignments for deleted nodes
                    cached_assignments = {k: v for k, v in cached_assignments.items() 
                                         if k in current_nodes}
        
        # Cluster (or use cache)
        if cached_assignments:
            print("📂 Using cached cluster assignments")
            self._create_agents_from_assignments(cached_assignments)
        else:
            if method == "hybrid":
                self._create_agents_hybrid()
            else:
                self._create_agents_label_propagation()
            
            # Save for next time
            assignments = {nid: aid for nid, aid in self.node_to_agent.items()}
            self.persistence.save_assignments(assignments, method)
        
        # Build agent adjacency
        self._build_agent_adjacency()
        
        self._initialized = True
        
        print(f"\n✅ Router initialized")
        print(f"   Nodes: {len(self.nodes)}")
        print(f"   Edges: {len(self.edges)}")
        print(f"   Agents: {len(self.agents)}")
        
        return True
    
    def _validate_edge_collections(self):
        """Check which edge collections exist"""
        all_colls = [c['name'] for c in self.db.collections() if not c['name'].startswith('_')]
        self.available_edge_collections = [ec for ec in EDGE_COLLECTIONS if ec in all_colls]
        print(f"✓ Found {len(self.available_edge_collections)} edge collections")
    
    def _load_nodes(self):
        """Load all data nodes"""
        all_colls = [c['name'] for c in self.db.collections() if not c['name'].startswith('_')]
        data_colls = [c for c in all_colls 
                      if c not in SCHEMA_COLLECTIONS and c not in EDGE_COLLECTIONS]
        
        print(f"📊 Loading nodes from {len(data_colls)} collections...")
        
        self.nodes.clear()
        for coll_name in data_colls:
            try:
                for doc in self.db.aql.execute(f"FOR d IN `{coll_name}` RETURN d"):
                    tags = doc.get("tags", [])
                    if isinstance(tags, str):
                        tags = [tags]
                    
                    self.nodes[doc["_id"]] = GraphNode(
                        id=doc["_id"],
                        label=doc.get("name", doc.get("label", doc.get("_key", ""))),
                        node_type=doc.get("type", "unknown"),
                        team_cluster=doc.get("cluster", "unknown"),
                        description=doc.get("description", ""),
                        tags=tags,
                        properties={k: v for k, v in doc.items() if k not in ['_id', '_key', '_rev']}
                    )
            except Exception as e:
                print(f"⚠️ Error loading {coll_name}: {e}")
        
        print(f"✓ Loaded {len(self.nodes)} nodes")
    
    def _load_edges(self):
        """Load all edges"""
        node_ids = set(self.nodes.keys())
        self.edges.clear()
        
        for edge_coll in self.available_edge_collections:
            try:
                for e in self.db.aql.execute(f"FOR e IN `{edge_coll}` RETURN e"):
                    if e["_from"] in node_ids and e["_to"] in node_ids:
                        self.edges.append(GraphEdge(
                            id=e["_id"],
                            source=e["_from"],
                            target=e["_to"],
                            edge_type=edge_coll,
                            weight=PROPAGATION_WEIGHTS.get(edge_coll, 0.5)
                        ))
            except Exception as e:
                print(f"⚠️ Error loading {edge_coll}: {e}")
        
        print(f"✓ Loaded {len(self.edges)} edges")
    
    def _create_agents_hybrid(self):
        """Create agents using hybrid clustering"""
        clusterer = HybridClusterer(self.ollama, self.clustering_config)
        cluster_assignments, self.embeddings = clusterer.cluster(self.nodes, self.edges)
        
        self._create_agents_from_assignments(cluster_assignments)
    
    def _create_agents_from_assignments(self, assignments: Dict[str, str]):
        """Create agents from pre-computed assignments"""
        # Group by cluster
        cluster_nodes: Dict[str, Set[str]] = defaultdict(set)
        for node_id, cluster_id in assignments.items():
            cluster_nodes[cluster_id].add(node_id)
        
        # Compile cards and create agents
        compiler = ClusterCardCompiler(self.ollama)
        min_size = self.clustering_config["min_cluster_size"]
        
        print(f"🃏 Compiling ClusterCards...")
        
        self.agents.clear()
        self.node_to_agent.clear()
        
        for cluster_id, node_ids in cluster_nodes.items():
            if len(node_ids) < min_size:
                continue
            
            card = compiler.compile(
                cluster_id=cluster_id,
                node_ids=node_ids,
                nodes=self.nodes,
                edges=self.edges,
                all_clusters=assignments,
                embeddings=self.embeddings
            )
            
            agent = ClusterAgent(agent_id=f"agent_{cluster_id}", card=card)
            self.agents[agent.agent_id] = agent
            
            for nid in node_ids:
                self.node_to_agent[nid] = agent.agent_id
        
        print(f"✓ Created {len(self.agents)} agents with ClusterCards")
    
    def _create_agents_label_propagation(self):
        """Label propagation clustering (for comparison)"""
        adjacency: Dict[str, Set[str]] = defaultdict(set)
        for edge in self.edges:
            adjacency[edge.source].add(edge.target)
            adjacency[edge.target].add(edge.source)
        
        communities = {nid: nid for nid in self.nodes}
        
        for _ in range(15):
            changed = False
            node_ids = list(communities.keys())
            np.random.shuffle(node_ids)
            
            for nid in node_ids:
                neighbors = adjacency.get(nid, set())
                if not neighbors:
                    continue
                
                label_counts: Dict[str, int] = defaultdict(int)
                for neighbor in neighbors:
                    label_counts[communities[neighbor]] += 1
                
                if label_counts:
                    best = max(label_counts, key=label_counts.get)
                    if communities[nid] != best:
                        communities[nid] = best
                        changed = True
            
            if not changed:
                break
        
        unique = list(set(communities.values()))
        cmap = {old: f"cluster_{i}" for i, old in enumerate(unique)}
        assignments = {nid: cmap[cid] for nid, cid in communities.items()}
        
        self._create_agents_from_assignments(assignments)
    
    def _build_agent_adjacency(self):
        """Build agent adjacency from inter-cluster edges"""
        self.agent_adjacency.clear()
        
        for edge in self.edges:
            src = self.node_to_agent.get(edge.source)
            tgt = self.node_to_agent.get(edge.target)
            if src and tgt and src != tgt:
                self.agent_adjacency[src].add(tgt)
                self.agent_adjacency[tgt].add(src)
    
    def search(self, query: str, top_k: int = 5) -> ActivationResult:
        """Execute neural search"""
        start = time.time()
        
        if not self._initialized:
            self.initialize()
        
        if not self.agents:
            return ActivationResult(
                query=query, entry_agents=[], entry_scores={},
                activated_agents=[], contributing_agents=[],
                propagation_path=[], contexts={}, cluster_cards={},
                nodes_traversed=0, total_time_ms=0
            )
        
        print(f"\n🔍 Search: '{query[:60]}...'")
        
        # Extract query features
        query_mitre = extract_mitre_ids(query)
        query_tools = extract_tools(query)
        query_keywords = extract_keywords(query)
        query_emb = self.ollama.get_embedding(query) if self.ollama.health_check() else None
        
        # Score agents
        agent_scores: Dict[str, Dict[str, float]] = {}
        for aid, agent in self.agents.items():
            agent_scores[aid] = self._compute_agent_score(
                agent, query_emb, query_mitre, query_tools, query_keywords
            )
        
        # Select entry agents
        sorted_agents = sorted(agent_scores.items(), key=lambda x: x[1]["combined"], reverse=True)
        entry_agents = [aid for aid, s in sorted_agents[:top_k] 
                       if s["combined"] >= ACTIVATION_THRESHOLD or len([a for a in sorted_agents[:top_k] if a[1]["combined"] >= ACTIVATION_THRESHOLD]) < 2][:top_k]
        
        print(f"   Entry: {entry_agents}")
        
        # Propagation (BFS)
        activated = set(entry_agents)
        signals = {aid: agent_scores[aid]["combined"] for aid in entry_agents}
        prop_path = []
        
        queue = [(aid, 0, signals[aid]) for aid in entry_agents]
        visited = {aid: 0 for aid in entry_agents}
        
        while queue and len(activated) < MAX_ACTIVE_AGENTS:
            current, depth, signal = queue.pop(0)
            if depth >= MAX_HOPS:
                continue
            
            for neighbor in self.agent_adjacency.get(current, set()):
                if neighbor in visited and visited[neighbor] <= depth:
                    continue
                
                prop_sig = signal * SIGNAL_DECAY
                if prop_sig >= ACTIVATION_THRESHOLD:
                    activated.add(neighbor)
                    visited[neighbor] = depth + 1
                    signals[neighbor] = prop_sig
                    prop_path.append({
                        "from_agent": current, "to_agent": neighbor,
                        "signal": prop_sig, "hop": depth + 1
                    })
                    queue.append((neighbor, depth + 1, prop_sig))
        
        print(f"   Activated: {len(activated)}, Propagation: {len(prop_path)} hops")
        
        # Generate contexts
        contexts = {}
        contributing = []
        cluster_cards = {}
        
        for aid in sorted(activated, key=lambda a: signals.get(a, 0), reverse=True)[:10]:
            agent = self.agents[aid]
            agent.activation_count += 1
            cluster_cards[aid] = agent.card.to_dict()
            
            if self.ollama.health_check():
                ctx = self.ollama.generate_context(agent.card, query)
                if ctx:
                    contexts[aid] = ctx
                    contributing.append(aid)
            else:
                contexts[aid] = agent.card.to_summary_text()
                contributing.append(aid)
        
        elapsed = (time.time() - start) * 1000
        
        return ActivationResult(
            query=query,
            entry_agents=entry_agents,
            entry_scores={aid: agent_scores[aid] for aid in entry_agents},
            activated_agents=list(activated),
            contributing_agents=contributing,
            propagation_path=prop_path,
            contexts=contexts,
            cluster_cards=cluster_cards,
            nodes_traversed=len(self.nodes),
            total_time_ms=elapsed
        )
    
    def _compute_agent_score(
        self, agent: ClusterAgent,
        query_emb: Optional[np.ndarray],
        query_mitre: Set[str],
        query_tools: Set[str],
        query_keywords: Set[str]
    ) -> Dict[str, float]:
        """Compute relevance score for an agent"""
        card = agent.card
        scores = {"semantic": 0.0, "mitre": 0.0, "tools": 0.0, "keywords": 0.0}
        
        if query_emb is not None and card.centroid_embedding is not None:
            dot = np.dot(query_emb, card.centroid_embedding)
            norm = np.linalg.norm(query_emb) * np.linalg.norm(card.centroid_embedding)
            scores["semantic"] = float(dot / norm) if norm > 0 else 0.0
        
        if query_mitre and card.mitre_techniques:
            scores["mitre"] = len(query_mitre & card.mitre_techniques) / len(query_mitre)
        
        if query_tools and card.tools:
            scores["tools"] = len(query_tools & card.tools) / len(query_tools)
        
        if query_keywords and card.keywords:
            scores["keywords"] = len(query_keywords & card.keywords) / len(query_keywords | card.keywords)
        
        scores["combined"] = (
            0.4 * scores["semantic"] +
            0.25 * scores["mitre"] +
            0.25 * scores["tools"] +
            0.1 * scores["keywords"]
        )
        return scores
    
    # === API Methods ===
    
    def get_stats(self) -> Dict[str, Any]:
        """Get router statistics"""
        return {
            "initialized": self._initialized,
            "clustering_method": self.clustering_method,
            "clustering_config": self.clustering_config,
            "total_nodes": len(self.nodes),
            "total_edges": len(self.edges),
            "total_agents": len(self.agents),
            "edge_collections": self.available_edge_collections,
            "persistence_info": self.persistence.get_assignment_metadata(),
            "agent_stats": {
                aid: {
                    "nodes": agent.card.node_count,
                    "primary_type": agent.card.primary_type,
                    "primary_team": agent.card.primary_team,
                    "mitre": " ".join(list(agent.card.mitre_techniques)[:5]),
                    "tools": " ".join(list(agent.card.tools)[:5]),
                    "coherence": agent.card.coherence_score,
                    "connectivity": agent.card.connectivity_score,
                    "activations": agent.activation_count,
                }
                for aid, agent in self.agents.items()
            }
        }
    
    def get_agent_info(self, agent_id: str) -> Optional[Dict[str, Any]]:
        """Get detailed agent info"""
        agent = self.agents.get(agent_id)
        if not agent:
            return None
        return {
            "agent_id": agent.agent_id,
            **agent.card.to_dict(),
            "activation_count": agent.activation_count,
            "neighbors": list(self.agent_adjacency.get(agent_id, set()))
        }
    
    def get_all_agents(self) -> List[Dict[str, Any]]:
        """Get all agents summary"""
        return [
            {
                "agent_id": a.agent_id,
                "cluster_id": a.card.cluster_id,
                "node_count": a.card.node_count,
                "primary_type": a.card.primary_type,
                "primary_team": a.card.primary_team,
                "mitre": list(a.card.mitre_techniques)[:3],
                "tools": list(a.card.tools)[:3],
                "coherence": round(a.card.coherence_score, 2),
                "activation_count": a.activation_count,
            }
            for a in self.agents.values()
        ]
    
    def recluster(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Force re-clustering with optional new config"""
        if config:
            self.clustering_config.update(config)
        
        self.initialize(force_reload=True, method=self.clustering_method, 
                       use_cached=False, config=self.clustering_config)
        
        return self.get_stats()


# =============================================================================
# FASTAPI ENDPOINTS
# =============================================================================

def create_hybrid_router_endpoints(app, router: HybridClusterRouter):
    """Add hybrid router endpoints to FastAPI"""
    from fastapi import Query, HTTPException
    from pydantic import BaseModel
    
    class ClusterConfig(BaseModel):
        semantic_weight: Optional[float] = None
        edge_weight: Optional[float] = None
        type_bonus: Optional[float] = None
        team_bonus: Optional[float] = None
        merge_threshold: Optional[float] = None
        min_cluster_size: Optional[int] = None
        max_cluster_size: Optional[int] = None
    
    @app.get("/api/neural-v3/health")
    def neural_v3_health():
        return {
            "status": "ok",
            "version": "3.1-hybrid-persistent",
            "initialized": router._initialized,
            "method": router.clustering_method,
            "agents": len(router.agents),
            "nodes": len(router.nodes),
            "edges": len(router.edges),
        }
    
    @app.post("/api/neural-v3/initialize")
    def neural_v3_initialize(
        force: bool = False, 
        method: str = "hybrid",
        use_cached: bool = True
    ):
        success = router.initialize(force_reload=force, method=method, use_cached=use_cached)
        return {"success": success, "stats": router.get_stats()}
    
    @app.post("/api/neural-v3/recluster")
    def neural_v3_recluster(config: Optional[ClusterConfig] = None):
        """Force re-clustering with optional config changes"""
        cfg = config.dict(exclude_none=True) if config else None
        return router.recluster(cfg)
    
    @app.get("/api/neural-v3/search")
    def neural_v3_search(
        q: str = Query(..., description="Search query"),
        top_k: int = Query(5, description="Entry agents")
    ):
        result = router.search(q, top_k=top_k)
        return {
            "query": result.query,
            "entry_agents": result.entry_agents,
            "entry_scores": result.entry_scores,
            "activated_agents": result.activated_agents,
            "contributing_agents": result.contributing_agents,
            "propagation_path": result.propagation_path,
            "contexts": result.contexts,
            "cluster_cards": result.cluster_cards,
            "nodes_traversed": result.nodes_traversed,
            "time_ms": result.total_time_ms,
        }
    
    @app.get("/api/neural-v3/agents")
    def neural_v3_agents():
        return {"agents": router.get_all_agents(), "total": len(router.agents)}
    
    @app.get("/api/neural-v3/agent/{agent_id}")
    def neural_v3_agent_info(agent_id: str):
        info = router.get_agent_info(agent_id)
        if not info:
            raise HTTPException(404, f"Agent {agent_id} not found")
        return info
    
    @app.get("/api/neural-v3/stats")
    def neural_v3_stats():
        return router.get_stats()
    
    @app.get("/api/neural-v3/config")
    def neural_v3_config():
        """Get current clustering configuration"""
        return {
            "current": router.clustering_config,
            "defaults": DEFAULT_CLUSTERING_CONFIG
        }
    
    print("✓ Hybrid cluster router v3.1 endpoints at /api/neural-v3/*")


# =============================================================================
# STANDALONE TEST
# =============================================================================

if __name__ == "__main__":
    print("Testing Hybrid Cluster Router v2...")
    
    router = HybridClusterRouter()
    router.initialize(method="hybrid", use_cached=True)
    
    stats = router.get_stats()
    print(f"\n📊 Stats: {stats['total_nodes']} nodes, {stats['total_edges']} edges, {stats['total_agents']} agents")
    
    print("\n🃏 Cluster Cards:")
    for agent in router.get_all_agents():
        print(f"   {agent['agent_id']}: {agent['node_count']} nodes, "
              f"{agent['primary_team']}/{agent['primary_type']}, "
              f"coherence={agent['coherence']}")
    
    if stats['total_agents'] > 0:
        for query in ["credential dumping mimikatz", "lateral movement", "cobalt strike beacon"]:
            print(f"\n{'='*60}")
            result = router.search(query, top_k=3)
            print(f"Query: {query}")
            print(f"Entry: {result.entry_agents}")
            print(f"Activated: {len(result.activated_agents)}")
            print(f"Propagation: {len(result.propagation_path)} steps")
            print(f"Time: {result.total_time_ms:.1f}ms")