"""
Domain boundary for Coverage Analyst.
Auto-generated by ProtoGraph App Onboarding — edit freely.
"""

# OWL classes this agent can reason about
DOMAIN_CLASSES = ['Library Module', 'Execution Sequence', 'TTP']

# Relationship types in scope
DOMAIN_RELATIONSHIPS = []

# Write permissions granted
WRITE_PERMISSIONS = []

# Interaction mode: 'action' | 'conversational' | 'hybrid'
MODE = 'conversational'
